"""migracao_080225

Revision ID: d42dd00acf4b
Revises: 
Create Date: 2025-02-08 21:07:49.942832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42dd00acf4b'
down_revision = None
branch_labels = None
depends_on = None





def upgrade():
    # ### commands auto generated by Alembic - ajustado! ###
    with op.batch_alter_table('preferencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cep_padrao_loja', sa.String(length=9), nullable=True))
        batch_op.alter_column('taxa_marketplace',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)

    # Preencher valores nulos com um padrão antes de tornar NOT NULL
    op.execute("UPDATE preferencias SET cep_padrao_loja = '00000-000' WHERE cep_padrao_loja IS NULL")

    # Agora sim podemos definir a coluna como NOT NULL
    with op.batch_alter_table('preferencias', schema=None) as batch_op:
        batch_op.alter_column('cep_padrao_loja', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - ajustado! ###
    with op.batch_alter_table('preferencias', schema=None) as batch_op:
        batch_op.alter_column('cep_padrao_loja', nullable=True)
        batch_op.alter_column('taxa_marketplace',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
        batch_op.drop_column('cep_padrao_loja')

    # ### end Alembic commands ###

