"""migracao3_100225

Revision ID: fe4af5082d19
Revises: 37e460409a9f
Create Date: 2025-02-10 10:42:04.238444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe4af5082d19'
down_revision = '37e460409a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('endereco',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('cep',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('cidade',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
        batch_op.alter_column('cidade',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('cep',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('endereco',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    op.drop_table('admin')
    # ### end Alembic commands ###
